services:
  - type: web
    name: album-del-amor
    env: node
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: album-amor-db
          property: connectionString

databases:
  - name: album-amor-db
    databaseName: albumamor
    plan: free
